name: Docker Image CI

on:
  push:
    branches: [ "go1.20-v1.7.1" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test Enviroment
      env: 
        registry: ${{ vars.ALIYUN_SHENZHEN_REGISTRY }}
      run: echo $registry
