name: Docker Image CI

on:
  push:
    branches: [ "go1.20-v1.7.1" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    environment: 
      name: public-builder
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download Archive Files
      run: sh dl.sh
    - name: Login to Hub
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ vars.ALIYUN_SHENZHEN_REGISTRY }}
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ vars.ALIYUN_SHENZHEN_REGISTRY }}/vim
    - name: Build and push Docker image
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        file: ./tabnine.dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
