name: Docker Image CI

on:
  push:
    branches: [ "go1.20-v1.7.1" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test Enviroment
      env: 
        registry: registry.cn-shenzhen.aliyuncs.com
      run: echo $registry
    - name: Login Registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: registry.cn-shenzhen.aliyuncs.com
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
      secrets:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
      env:
        registry: ${{ env.ALIYUN_SHENZHEN_REGISTRY }}
    - name: Download Archive Files
      run: sh dl.sh
